NewUniversityProejct/NewUniversityProejct/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UniversityProject.Models;
using PagedList;
using System.Data.Entity;
using NewUniversityProejct.Models;

namespace UniversityProject.Controllers
{
    public class GameController : Controller
    {
        private GameCatalogDbContext db = new GameCatalogDbContext();
        // GET: Default
        public ActionResult Index(int? page, string nameSearch, string sortOrder)
        {
            int pageNumber = page ?? 1;
            int pageSize = 5;
            IQueryable<Game> game = db.Game.AsQueryable();

            ViewBag.NameSearch = nameSearch;
            if (!String.IsNullOrEmpty(nameSearch) && this.User.Identity.IsAuthenticated)
            {
                game = game.Where(x => x.Name.Contains(nameSearch));
            }

            ViewBag.CurrentSortParm = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.GenreSortParm = sortOrder == "genre_asc" ? "genre_desc" : "genre_asc";
            ViewBag.RatingSortParm = sortOrder == "rating_asc" ? "rating_desc" : "rating_asc";
            var a = game.ToList();
            switch (sortOrder)
            {
                case "name_desc":
                    game = game.OrderByDescending(x => x.Name);
                    break;
                case "genre_asc":
                    game = game.OrderBy(x => x.Genre.GenreName);
                    break;
                case "genre_desc":
                    game = game.OrderByDescending(x => x.Genre.GenreName);
                    break;
                case "rating_asc":
                    game = game.OrderBy(x => x.Rating.RatingValue);
                    break;
                case "rating_desc":
                    game = game.OrderByDescending(x => x.Rating.RatingValue);
                    break;
                default:
                    game = game.OrderBy(x => x.Name);
                    break;
            }

            return View(game.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult Create()
        {
            ViewBag.Rating = new SelectList(db.Rating, "Id", "RatingValue");
            ViewBag.Genre = new SelectList(db.Genre, "Id", "GenreName");

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Game game)
        {
            //[Bind(Include = "Id,Name,ReleaseYear,GenreId,RatingId,")] 
            if (ModelState.IsValid)
            {
                db.Game.Add(game);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Rating = new SelectList(db.Rating, "Id", "RatingValue");
            ViewBag.Genre = new SelectList(db.Genre, "Id", "GenreName");

            return View(game);
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Game.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }
            return View(game);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Game.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }

            ViewBag.Rating = db.Rating;
            ViewBag.Genre = db.Genre;

            return View(game);
        }
        [Authorize]
        [HttpPost]
        public ActionResult Edit(Game model)
        {
            if (!ModelState.IsValid)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (model != null)
            {
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Rating = db.Rating;
            ViewBag.Genre = db.Genre;

            return View(model);
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Game.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }
            return View(game);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Game game = db.Game.Find(id);
            db.Game.Remove(game);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

NewUniversityProejct/NewUniversityProejct/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link href="~/Content/simple-sidebar.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <title>@ViewBag.Title - Online Game Catalog</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body class="mainBody">

    <div id="wrapper">
        <div id="sidebar-wrapper">
            @if (User.IsInRole("Admin"))
            {
                <ul class="sidebar-nav">
                    <li class="sidebar-brand">
                        @Html.ActionLink("My Games", "Index", "Game", new { area = "" }, new { @class = "navbar-brand" })

                    </li>
                </ul>
            }
            else
            {
                <ul class="sidebar-nav">
                    <li class="sidebar-brand">
                        @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

                    </li>
                </ul>
            }

            @if (Request.IsAuthenticated)
            {
                using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                {
                    @Html.AntiForgeryToken()
                    <ul class="sidebar-nav" style="margin-top:70px">
                        <li>
                            @Html.ActionLink(User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
                        </li>
                        <li>@Html.ActionLink("Home", "", "Home")</li>
                        <li>@Html.ActionLink("Genre", "", "Genre")</li>
                        <li>@Html.ActionLink("Rating", "", "Rating")</li>
                        <li>@Html.ActionLink("Roles", "", "Roles")</li>

                        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                    </ul>
                }
            }
            else
            {
                    <ul class="sidebar-nav" style="margin-top:70px">
                        @if (User.IsInRole("Admin"))
                        {

                            <li>@Html.ActionLink("Genre", "", "Genre")</li>
                            <li>@Html.ActionLink("Rating", "", "Rating")</li>
                            <li>@Html.ActionLink("Roles", "", "Roles")</li>
                        }
                        <li>@Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>

                        <li>@Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>

                    </ul>
            }
        </div>
        <div class="container" style="position:relative;top:20px;left:20px">
            <partial name="_CookieConsentPartial" />
            <main role="main" class="pd-3">
                <a href="#menu-toggle" class="btn btn-danger menuBtn" id="menu-toggle"><span class="glyphicon glyphicon-menu-hamburger"></span></a>
                @RenderBody()
            </main>
        </div>
        
    </div>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
    </script>
    <script type="text/javascript"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    

    <script>
            $(document).ready(function () {
                $("#menu-toggle").click(function (e) {
                    e.preventDefault();
                    $("#wrapper").toggleClass("toggled");
                });
        });
    </script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>